//go:build windows

package bootstrap

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// bootstrapOS performs the Windows-specific bootstrap: resolve a MinGW UCRT64
// toolchain + OpenSSL, fetch tap-windows.h, generate the machine-specific
// cgo_openssl_local.go (-I/-L for OpenSSL), and patch the vendored call.hpp so
// the OpenVPN3 core spawns netsh/route/ipconfig with no visible window.
func bootstrapOS(root string, opts Options) error {
	if err := fetchTapWindows(root, opts); err != nil {
		return err
	}

	ucrt := resolveUCRT64()
	if ucrt == "" {
		opts.logf("WARN: no UCRT64 OpenSSL found; set LENSR_UCRT64 or CGO_CPPFLAGS/CGO_LDFLAGS manually")
	} else {
		opts.logf("openvpn: UCRT64 toolchain at %s", ucrt)
		if err := genOpenSSLFlags(root, ucrt, opts); err != nil {
			return err
		}
	}

	if err := patchCallHpp(root, opts); err != nil {
		opts.logf("WARN: patch call.hpp: %v", err)
	}
	return nil
}

// RuntimeDLLSourceDir returns the directory the 5 runtime DLLs (see
// openvpn3.RuntimeDLLs) are copied FROM on this machine — the resolved UCRT64
// bin dir. Empty if no toolchain is found. Used by release packaging.
func RuntimeDLLSourceDir() string {
	if u := resolveUCRT64(); u != "" {
		return filepath.Join(u, "bin")
	}
	return ""
}

// resolveUCRT64 finds a UCRT64 root that ships OpenSSL dev headers. Order:
// LENSR_UCRT64, scoop msys2, C:\msys64. Empty if none validate.
func resolveUCRT64() string {
	var candidates []string
	if v := os.Getenv("LENSR_UCRT64"); v != "" {
		candidates = append(candidates, v)
	}
	if up := os.Getenv("USERPROFILE"); up != "" {
		candidates = append(candidates, filepath.Join(up, "scoop", "apps", "msys2", "current", "ucrt64"))
	}
	candidates = append(candidates, `C:\msys64\ucrt64`)

	for _, c := range candidates {
		if fileExists(filepath.Join(c, "include", "openssl", "opensslv.h")) {
			return c
		}
	}
	return ""
}

// genOpenSSLFlags writes cgo_openssl_local.go in the module root with the
// machine-specific OpenSSL include/lib paths (gitignored, regenerated).
func genOpenSSLFlags(root, ucrt string, opts Options) error {
	ssl := strings.ReplaceAll(ucrt, `\`, "/")
	content := fmt.Sprintf(`//go:build windows && cgo

// Code generated by openvpn3-go bootstrap. DO NOT EDIT.
// Machine-specific OpenSSL paths for the UCRT64 toolchain; gitignored.
package openvpn3

// #cgo CPPFLAGS: -I%s/include
// #cgo LDFLAGS: -L%s/lib
import "C"
`, ssl, ssl)

	out := filepath.Join(root, "cgo_openssl_local.go")
	if err := os.WriteFile(out, []byte(content), 0o644); err != nil {
		return err
	}
	opts.logf("openvpn: generated %s", out)
	return nil
}

// fetchTapWindows clones tap-windows6 and copies its tap-windows.h header into
// deps/tap-windows/include (idempotent).
func fetchTapWindows(root string, opts Options) error {
	inc := filepath.Join(root, "deps", "tap-windows", "include")
	hdr := filepath.Join(inc, "tap-windows.h")
	if !opts.Force && fileExists(hdr) {
		opts.logf("[skip] tap-windows.h present")
		return nil
	}
	tmp, err := os.MkdirTemp("", "tapwin6")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(tmp) }()

	if err := run(root, "git", "clone", "--depth", "1", "https://github.com/OpenVPN/tap-windows6.git", tmp); err != nil {
		return err
	}
	if err := os.MkdirAll(inc, 0o755); err != nil {
		return err
	}
	src, err := os.ReadFile(filepath.Join(tmp, "src", "tap-windows.h"))
	if err != nil {
		return fmt.Errorf("read tap-windows.h: %w", err)
	}
	opts.logf("[fetch] tap-windows.h")
	return os.WriteFile(hdr, src, 0o644)
}

var creationFlagsRE = regexp.MustCompile(`(?m)^(\s*)0,(\s*)// creation flags`)

// patchCallHpp makes the vendored OpenVPN3 command runner spawn child processes
// (netsh/route/ipconfig) with no visible window. Idempotent; re-applied each run
// since a submodule update restores the pristine file.
func patchCallHpp(root string, opts Options) error {
	p := filepath.Join(root, "openvpn", "openvpn", "win", "call.hpp")
	if !fileExists(p) {
		return nil // core not present yet
	}
	b, err := os.ReadFile(p)
	if err != nil {
		return err
	}
	src := string(b)
	orig := src

	if !strings.Contains(src, "CREATE_NO_WINDOW") {
		src = creationFlagsRE.ReplaceAllString(src, "${1}CREATE_NO_WINDOW,${2}// creation flags (lensr: hide netsh/route child windows)")
	}
	if !strings.Contains(src, "STARTF_USESHOWWINDOW") {
		src = strings.Replace(src,
			"siStartInfo.dwFlags |= STARTF_USESTDHANDLES;",
			"siStartInfo.dwFlags |= STARTF_USESTDHANDLES | STARTF_USESHOWWINDOW;\n    siStartInfo.wShowWindow = SW_HIDE; // lensr: hide netsh/route child windows",
			1)
	}
	if src == orig {
		return nil
	}
	opts.logf("openvpn: patched call.hpp (hide child windows)")
	return os.WriteFile(p, []byte(src), 0o644)
}
