//go:build windows

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// setupOpenSSL finds an OpenSSL dev install and writes the gitignored
// cgo_openssl_local.go in the module root so local cgo builds need no env.
// Maintainer/dev convenience only — consumers set CGO_CPPFLAGS/CGO_LDFLAGS
// instead (see README "Linking OpenSSL").
func setupOpenSSL(root string) error {
	ssl := resolveOpenSSL()
	if ssl == "" {
		return fmt.Errorf("no OpenSSL dev install found; set OPENVPN3_SSLDIR to a dir containing include/openssl and lib, or set CGO_CPPFLAGS/CGO_LDFLAGS manually")
	}
	fmt.Fprintf(os.Stderr, "openvpn: OpenSSL at %s\n", ssl)

	fwd := strings.ReplaceAll(ssl, `\`, "/")
	content := fmt.Sprintf(`//go:build windows && cgo

// Code generated by "openvpn bootstrap". DO NOT EDIT.
// Machine-specific OpenSSL paths; gitignored.
package openvpn3

// #cgo CPPFLAGS: -I%s/include
// #cgo LDFLAGS: -L%s/lib
import "C"
`, fwd, fwd)

	out := filepath.Join(root, "cgo_openssl_local.go")
	if err := os.WriteFile(out, []byte(content), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "openvpn: generated %s\n", out)
	return nil
}

// resolveOpenSSL finds a root that ships OpenSSL dev headers. Order:
// OPENVPN3_SSLDIR, LENSR_UCRT64 (legacy), scoop msys2 ucrt64, scoop mingw opt,
// C:\msys64\ucrt64. Empty if none validate.
func resolveOpenSSL() string {
	var candidates []string
	for _, env := range []string{"OPENVPN3_SSLDIR", "LENSR_UCRT64"} {
		if v := os.Getenv(env); v != "" {
			candidates = append(candidates, v)
		}
	}
	if up := os.Getenv("USERPROFILE"); up != "" {
		candidates = append(candidates,
			filepath.Join(up, "scoop", "apps", "msys2", "current", "ucrt64"),
			filepath.Join(up, "scoop", "apps", "mingw", "current", "opt"),
		)
	}
	candidates = append(candidates, `C:\msys64\ucrt64`)

	for _, c := range candidates {
		if fi, err := os.Stat(filepath.Join(c, "include", "openssl", "opensslv.h")); err == nil && !fi.IsDir() {
			return c
		}
	}
	return ""
}
